#!/usr/bin/env bash
# setup-worktree.sh
# Usage: ./scripts/setup-worktree.sh <branch-name>
# Creates a git worktree with unique port assignment for the given branch.

set -euo pipefail

BRANCH="${1:-}"
if [[ -z "$BRANCH" ]]; then
  echo "Usage: $0 <branch-name>" >&2; exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
PROJECT_NAME="$(node -e "process.stdout.write(require('$REPO_ROOT/package.json').name)")"

# Hash branch name to get stable port offset in [1..899]
OFFSET="$(echo "$BRANCH" | cksum | awk '{print ($1 % 900) + 1}')"
DB_PORT=$((5432 + OFFSET))
API_PORT=$((3000 + OFFSET))
WEB_PORT=$((5173 + OFFSET))
REDIS_PORT=$((6379 + OFFSET))

SAFE_BRANCH="${BRANCH//\//-}"
WORKTREE_DIR="$(dirname "$REPO_ROOT")/${PROJECT_NAME}-${SAFE_BRANCH}"

echo "Creating worktree at: $WORKTREE_DIR"
echo "  Branch  : $BRANCH"
echo "  DB_PORT : $DB_PORT"
echo "  API_PORT: $API_PORT"
echo "  WEB_PORT: $WEB_PORT"
echo "  REDIS   : $REDIS_PORT"

if ! git -C "$REPO_ROOT" show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "Branch '$BRANCH' not found, creating from HEAD..."
  git -C "$REPO_ROOT" branch "$BRANCH"
fi

git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" "$BRANCH"

SAFE_DB_NAME="${BRANCH//[^a-zA-Z0-9]/_}"
cat > "$WORKTREE_DIR/.env.worktree" <<ENV_FILE
# Auto-generated by scripts/setup-worktree.sh
# Branch: $BRANCH | Offset: $OFFSET
NODE_ENV=development
PORT=$API_PORT
WEB_PORT=$WEB_PORT
DB_HOST=localhost
DB_PORT=$DB_PORT
DB_NAME=${PROJECT_NAME}_${SAFE_DB_NAME}
DB_USER=postgres
DB_PASSWORD=postgres
DATABASE_URL=postgresql://postgres:postgres@localhost:${DB_PORT}/${PROJECT_NAME}_${SAFE_DB_NAME}?schema=public
REDIS_HOST=localhost
REDIS_PORT=$REDIS_PORT
REDIS_URL=redis://localhost:$REDIS_PORT
VITE_API_URL=http://localhost:$API_PORT
CORS_ORIGIN=http://localhost:$WEB_PORT
WORKTREE_BRANCH=$BRANCH
WORKTREE_OFFSET=$OFFSET
ENV_FILE

echo "Written .env.worktree"

OVERLAY_SRC="$REPO_ROOT/docker-compose.worktree.yml"
if [[ -f "$OVERLAY_SRC" ]]; then
  sed -e "s/\${DB_PORT}/$DB_PORT/g" -e "s/\${REDIS_PORT}/$REDIS_PORT/g"       -e "s/\${API_PORT}/$API_PORT/g" -e "s/\${WEB_PORT}/$WEB_PORT/g"       -e "s/\${BRANCH}/$SAFE_BRANCH/g"       "$OVERLAY_SRC" > "$WORKTREE_DIR/docker-compose.worktree.yml"
  echo "Copied docker-compose.worktree.yml"
fi

echo ""
echo "Worktree ready. To boot:"
echo "  cd $WORKTREE_DIR && ./scripts/boot.sh"
